// <auto-generated />
using System;
using Kestridge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kestridge.Api.Data.Migrations
{
    [DbContext(typeof(KestridgeDbContext))]
    [Migration("20260909210321_SiteContent")]
    partial class SiteContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kestridge.Api.Data.AdminAccount", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("display_name");

                    b.Property<ushort>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime?>("FirstFailedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_failed_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password_hash")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PasswordHash"), "ascii");

                    b.Property<ulong>("TotpLastStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasDefaultValue(0ul)
                        .HasColumnName("totp_last_step");

                    b.Property<string>("TotpSecret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("totp_secret")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TotpSecret"), "ascii");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("username")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Username"), "ascii");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uk_admin_accounts_username");

                    b.ToTable("admin_accounts", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.AdminSession", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TokenHash"), "ascii");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("absolute_expires_at");

                    b.Property<ulong>("AccountId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("IdleExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("idle_expires_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at");

                    b.HasKey("TokenHash");

                    b.HasIndex("AbsoluteExpiresAt")
                        .HasDatabaseName("ix_admin_sessions_expiry");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_admin_sessions_account");

                    b.ToTable("admin_sessions", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.ContactSubmission", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("dedupe_key")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DedupeKey"), "ascii");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<string>("HandledBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("handled_by");

                    b.Property<bool>("LegalHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("legal_hold");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("notified_at");

                    b.Property<byte>("NotifyAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("notify_attempts");

                    b.Property<string>("NotifyError")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasDefaultValue("")
                        .HasColumnName("notify_error");

                    b.Property<DateTime?>("NotifyNextAttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("notify_next_attempt_at");

                    b.Property<string>("NotifyState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("pending")
                        .HasColumnName("notify_state")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NotifyState"), "ascii");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("phone");

                    b.Property<DateOnly>("PurgeAfter")
                        .HasColumnType("date")
                        .HasColumnName("purge_after");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("service")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Service"), "ascii");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("uk_submissions_dedupe");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_submissions_email");

                    b.HasIndex("LegalHold", "PurgeAfter")
                        .HasDatabaseName("ix_submissions_purge");

                    b.HasIndex("NotifyState", "NotifyNextAttemptAt")
                        .HasDatabaseName("ix_submissions_notify");

                    b.ToTable("contact_submissions", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.DsrLogEntry", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AffectedIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("")
                        .HasColumnName("affected_ids")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("AffectedIds"), "ascii");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<string>("HandledBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("handled_by");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("request_type")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("RequestType"), "ascii");

                    b.Property<uint>("RowsAffected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("rows_affected");

                    b.Property<string>("SubjectEmailHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("subject_email_hash")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SubjectEmailHash"), "ascii");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedOn")
                        .HasDatabaseName("ix_dsr_received");

                    b.HasIndex("SubjectEmailHash")
                        .HasDatabaseName("ix_dsr_hash");

                    b.ToTable("dsr_log", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.JobRun", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateOnly?>("CutoffDate")
                        .HasColumnType("date")
                        .HasColumnName("cutoff_date");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasDefaultValue("")
                        .HasColumnName("detail");

                    b.Property<uint>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("duration_ms");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("job_name")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JobName"), "ascii");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("running")
                        .HasColumnName("outcome")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Outcome"), "ascii");

                    b.Property<uint>("RowsAffected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("rows_affected");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAt")
                        .HasDatabaseName("ix_job_runs_name_time");

                    b.ToTable("job_runs", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.SiteCompany", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Hidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("hidden");

                    b.Property<string>("LogoFile")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("logo_file")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LogoFile"), "ascii");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<uint>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("LogoFile")
                        .IsUnique()
                        .HasDatabaseName("uk_site_companies_file");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_site_companies_order");

                    b.ToTable("site_companies", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.SiteFaq", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("answer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("question");

                    b.Property<uint>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_site_faq_order");

                    b.ToTable("site_faq", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.SiteService", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("CardLabel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("card_label");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("description");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("icon_name")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("IconName"), "ascii");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("slug")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Slug"), "ascii");

                    b.Property<uint>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("sort_order");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("tagline");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uk_site_services_slug");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_site_services_order");

                    b.ToTable("site_services", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.SiteServiceHighlight", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("ServiceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("service_id");

                    b.Property<uint>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "SortOrder")
                        .HasDatabaseName("ix_site_service_highlights_service");

                    b.ToTable("site_service_highlights", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.SiteServiceStep", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("detail");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("phase");

                    b.Property<ulong>("ServiceId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("service_id");

                    b.Property<uint>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("sort_order");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "SortOrder")
                        .HasDatabaseName("ix_site_service_steps_service");

                    b.ToTable("site_service_steps", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.SiteTeamMember", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("focus");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("initials")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Initials"), "ascii");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("")
                        .HasColumnName("photo")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Photo"), "ascii");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("role");

                    b.Property<uint>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_site_team_order");

                    b.ToTable("site_team", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });
#pragma warning restore 612, 618
        }
    }
}
