// <auto-generated />
using System;
using Kestridge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kestridge.Api.Data.Migrations
{
    [DbContext(typeof(KestridgeDbContext))]
    partial class KestridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kestridge.Api.Data.ContactSubmission", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("dedupe_key")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DedupeKey"), "ascii");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email")
                        .UseCollation("utf8mb4_0900_as_cs");

                    b.Property<bool>("LegalHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("legal_hold");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("notified_at");

                    b.Property<byte>("NotifyAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("notify_attempts");

                    b.Property<string>("NotifyError")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasDefaultValue("")
                        .HasColumnName("notify_error");

                    b.Property<DateTime?>("NotifyNextAttemptAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("notify_next_attempt_at");

                    b.Property<string>("NotifyState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("pending")
                        .HasColumnName("notify_state")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NotifyState"), "ascii");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasDefaultValue("")
                        .HasColumnName("phone");

                    b.Property<DateOnly>("PurgeAfter")
                        .HasColumnType("date")
                        .HasColumnName("purge_after");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("service")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Service"), "ascii");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("uk_submissions_dedupe");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_submissions_email");

                    b.HasIndex("LegalHold", "PurgeAfter")
                        .HasDatabaseName("ix_submissions_purge");

                    b.HasIndex("NotifyState", "NotifyNextAttemptAt")
                        .HasDatabaseName("ix_submissions_notify");

                    b.ToTable("contact_submissions", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.DsrLogEntry", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AffectedIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("")
                        .HasColumnName("affected_ids")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("AffectedIds"), "ascii");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<string>("HandledBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("handled_by");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("request_type")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("RequestType"), "ascii");

                    b.Property<uint>("RowsAffected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("rows_affected");

                    b.Property<string>("SubjectEmailHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("subject_email_hash")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SubjectEmailHash"), "ascii");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedOn")
                        .HasDatabaseName("ix_dsr_received");

                    b.HasIndex("SubjectEmailHash")
                        .HasDatabaseName("ix_dsr_hash");

                    b.ToTable("dsr_log", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });

            modelBuilder.Entity("Kestridge.Api.Data.JobRun", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateOnly?>("CutoffDate")
                        .HasColumnType("date")
                        .HasColumnName("cutoff_date");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasDefaultValue("")
                        .HasColumnName("detail");

                    b.Property<uint>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("duration_ms");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("job_name")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JobName"), "ascii");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("running")
                        .HasColumnName("outcome")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Outcome"), "ascii");

                    b.Property<uint>("RowsAffected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("rows_affected");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "StartedAt")
                        .HasDatabaseName("ix_job_runs_name_time");

                    b.ToTable("job_runs", (string)null);

                    b.HasAnnotation("MySql:StoreOptions", "ROW_FORMAT=DYNAMIC");
                });
#pragma warning restore 612, 618
        }
    }
}
